version: "3.9"
services:
  proxy:
    build: .
    ports:
      - "3389:3389"
    environment:
      - GUACAMOLE_API=https://bssone.workspaces.bss-lab.it/api
      - GUACAMOLE_DB_HOST=bssone.workspaces.bss-lab.it
      - GUACAMOLE_DB_USER=guac_adm
      - GUACAMOLE_DB_PASS=guacamole